### PR TITLE
Add download of median streamflow from NWM

### LINKED ISSUE #5: Add streamflow
How can we do this? Is there a modeled discharge for CONUS using comid? 

Thus far have tried stream order, but wasn't useful.

### PR DESCRIPTION
**Pull request by lindsayplatt**
Fixes #5. This PR contains code that downloads NWM streamflow output from the S3 amazon bucket for a set of NHD COMIDs and then summarizes into median values. Total run time on my computer to download this data for just under 400 COMIDs was 4.5 hours. 

I'm a little skeptical of these values. I joined these NWM median streamflow values to the known USGS NWIS ones and it doesn't look great. I think I might need to 

- [x] first, verify that `feature_id` is the same as `COMID`, and then
- [x] verify that these COMIDs are being downloaded in the order I expect (otherwise I am saving them with the incorrect data). 

image

```r
library(targets)
library(tidyverse)

tar_load(p1_nwis_site_nhd_comid_ALL_xwalk)
tar_load(p1_nwm_streamflow)
tar_load(p2_attr_flow)

comid_q <- p1_nwis_site_nhd_comid_ALL_xwalk %>% 
  left_join(p2_attr_flow) %>% 
  rename(attr_medianFlowNWIS = attr_medianFlow) %>% 
  left_join(p1_nwm_streamflow) %>% 
  na.omit()

ggplot(comid_q, aes(x = attr_medianFlowNWIS, y = attr_medianFlowNWM)) +
  geom_point(shape=1) +
  ggtitle(sprintf('NWIS vs NWM Median Streamflow for %s sites', 
                  nrow(comid_q))) +
  theme_bw()
```

### CODE REVIEW

**Comment by lindsayplatt** [comment]
Hmmm this might be my answer. This [NWM document](https://www.weather.gov/media/owp/operations/Public_Handbook_NWC_Visualization_Services.pdf) references a crosswalk between NWM `feature_id` and NHD `ComID`. Might need to do some digging to find that.

image

**Comment by lindsayplatt** [comment]
Hmmm but this code in `nwmTools` makes it look like `feature_id` == `comid` ??

https://github.com/mikejohnson51/nwmTools/blob/e61bc3a1c54fb3c58b4471bf98e5fdfb8ded4dc3/data-raw/example_timeseries.R#L14-L21

**Comment by lindsayplatt** [comment]
And this sort of confirms my suspicion - the comid is just checked to make sure it appears in the `feature_id` list. https://github.com/mikejohnson51/nwmTools/blob/e61bc3a1c54fb3c58b4471bf98e5fdfb8ded4dc3/R/utils-readNWM.R#L140

**Comment by lindsayplatt** [comment]
A ha! I think the column orders in the returned data are always in numeric order of the COMIDs. This means that when I was saving the data out, I may have been misaligning the COMID with the output data because I kept the COMIDs in the same order.

For example, I just did a test where I grabbed data individually for two comids, `6078267` and `1777616`. Then, I tried both together where I passed in the higher number first `c(6078267, 1777616)`. The output order of the columns when I requested both is in numeric order by COMID (the opposite of what I requested).

image

**Comment by lindsayplatt** [comment]
Yay! Now that I have assigned the correct data to the appropriate COMID, the streamflow from NWM follows more of a linear relationship to the NWIS streamflow (esp when both are logged). I need to figure out the units, though because the 1:1 line (red) is way lower.

image

image

```r
library(targets)
library(tidyverse)

tar_load(p1_nwis_site_nhd_comid_ALL_xwalk)
tar_load(p1_nwm_streamflow)
tar_load(p2_attr_flow)

comid_q <- p1_nwis_site_nhd_comid_ALL_xwalk %>% 
  left_join(p2_attr_flow) %>% 
  rename(attr_medianFlowNWIS = attr_medianFlow) %>% 
  left_join(p1_nwm_streamflow) %>% 
  na.omit()# %>% 
  # slice(-130) # Remove the highest for visualization 

ggplot(comid_q, aes(x = log10(attr_medianFlowNWIS),
                    y = log10(attr_medianFlowNWM))) +
  geom_point(shape=1) +
  ggtitle(sprintf('NWIS vs NWM Median Streamflow for %s sites', 
                  nrow(comid_q))) +
  theme_bw() 

ggplot(comid_q, aes(x = attr_medianFlowNWIS,
                    y = attr_medianFlowNWM)) +
  geom_point(shape=1) +
  ggtitle(sprintf('NWIS vs NWM Median Streamflow for %s sites', 
                  nrow(comid_q))) +
  theme_bw() +
  geom_abline(slope = 1, intercept = 0, color = 'red')
```

**Comment by lindsayplatt** [comment]
So `medianFlow` is now an attribute passed in but did not come out of the model as important.

**Comment by lindsayplatt** [comment]
OK, so the units are as I expected (m3/s) so the NWIS and NHM flow values are in the same units _**except**_ that there is some scaling factor applied from NWM.

image

If you multiple `NWM` flow by the scaling factor, you get a better 1:1.

image

```r
library(targets)
library(tidyverse)

tar_load(p1_nwis_site_nhd_comid_ALL_xwalk)
tar_load(p1_nwm_streamflow)
tar_load(p2_attr_flow)


comid_q <- p1_nwis_site_nhd_comid_ALL_xwalk %>% 
  left_join(p2_attr_flow) %>% 
  rename(attr_medianFlowNWIS = attr_medianFlow) %>% 
  left_join(p1_nwm_streamflow) %>% 
  mutate(attr_medianFlowNWM_adj = attr_medianFlowNWM*0.009999999776482582) %>% 
  na.omit()

ggplot(comid_q, aes(x = attr_medianFlowNWIS,
                    y = attr_medianFlowNWM_adj)) +
  geom_point(shape=1) +
  ggtitle(sprintf('NWIS vs NWM Median Streamflow for %s sites', 
                  nrow(comid_q))) +
  theme_bw() +
  geom_abline(slope = 1, intercept = 0, color = 'red')
```

**Comment by tungttnguyen** [comment]
Hi Lindsay. I want to try this example. Can you show me where I can get `p1_nwis_site_nhd_comid_ALL_xwalk`, `p1_nwm_streamflow` and `p2_attr_flow`? Thanks!

**Pull request merged**
